name: Build and Run C Code

on:
  workflow_dispatch:
    inputs:
      c_file:
        description: 'Path to the C file to compile and run'
        required: true
        default: 'user-1/main.c'  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install build-essential  

    - name: Compile C code
      run: gcc -o my_program ${{ github.event.inputs.c_file }}  

    - name: Run the program
      run: ./my_program  
