name: Merge Branch

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  check-main-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/permissions

      - name: Set Git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get latest main branch
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          git pull origin ${{ github.base_ref }}

      - name: Check for ongoing merges
        run: |
          if git rev-parse --verify MERGE_HEAD >/dev/null 2>&1; then
            echo "Error: A merge is already in progress. Please wait until the current merge is completed.";
            exit 1;
          fi

      - name: Check for merge conflicts
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          git merge --no-commit pr-branch || { echo "Error: Merge conflict detected. Please resolve conflicts before merging."; exit 1; }

      - name: Merge PR into main
        run: |
          git merge --no-ff pr-branch
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.base_ref }}
